"""
Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
"""

class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        # use dict
        sDict, tDict = {}, {}
        for i in s:
            sDict[i] = sDict.get(i, 0) + 1
        for i in t:
            tDict[i] = tDict.get(i, 0) + 1
        for letter in tDict:
            if letter not in sDict:
                return letter
            if tDict[letter] != sDict[letter]:
                return letter

class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        # use bit manipulation
        result = 0
        for i in s:
            result ^= ord(i)
        for i in t:
            result ^= ord(i)
        return chr(result)